apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: basic-nginx
  namespace: default
spec:
  virtualhost:
    fqdn: nginx.exampledomain.com
    aliases:
    - nginx-1.exampledomain.com
  # tls:
  #   secretName: testsecret
  routes:
  - match: /
    services:
    - name: nginx-1
      port: 80

