apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: multi
  namespace: default
spec:
  virtualhost:
    fqdn: multi.exampledomain.com
  routes:
  - match: /
    services:
    - name: nginx-1-multi
      port: 80
      weight: 90
    - name: nginx-2-multi
      port: 80
      weight: 10
      # healthCheck:
      #   path: /healthy
      #   intervalSeconds: 5
      #   timeoutSeconds: 2
      #   unhealthyThresholdCount: 3
      #   healthyThresholdCount: 5

