apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx-2
  name: nginx-2
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-2
    spec:
      containers:
      - image: rosskukulinski/nginx-2
        imagePullPolicy: Always
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-2
  name: nginx-2
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-2
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-2-multi
  name: nginx-2-multi
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-2
  sessionAffinity: None
  type: ClusterIP